Qbox-project/qbx_core

- qbcore.sql
- server/functions.lua
- server/player.lua
It doesn't fix an issue but removed an unused column from the database.
I didn't load the server setter shit because im lazy.
- [x ] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [ x] My code fits the style guidelines.
- [ x] My PR fits the contribution guidelines.
> tweak: remove cid column

- .vscode/extensions.json
https://marketplace.visualstudio.com/items?itemName=overextended.cfxlua-vscode
Adds declarations for functions and types added by the Lua Script Runtime, LuaGLM language, environmental globals, and (FiveM/CFX) natives.
Prevents syntax errors when using safe navigation.
> chore: recommended cfxlua-vscode

- server/functions.lua
🎨 : ## Description
This pull request reworks some nested requirements that impede the readability of the ```functions.lua``` file. Functionality should remain exactly the same as the basic logic has not been changed. Nesting has been improved by using more guard clauses and removing else statements.
This is just a proof of concept for the moment, am unable to personally test due to my VM currently not being set up.
> Basic Readibility for functions.lua

- server/functions.lua
You know what it does and why it needs to be implemented
> refactor(server): CreateVehicleServerSetter is better

- client/events.lua
- client/functions.lua
- client/loops.lua
- client/main.lua
- config.lua
- fxmanifest.lua
- locale/en.lua
- server/commands.lua
- server/debug.lua
- server/events.lua
- server/exports.lua
- server/functions.lua
- server/loops.lua
- server/main.lua
- server/player.lua
- shared/gangs.lua
- shared/jobs.lua
- shared/locale.lua
- shared/locations.lua
- shared/main.lua
- Added #13 
- Formatted all string key lookups for tables to be just variables, because it's possible
- added an IsLoggedIn variable to not go through deserialization with the state each time
- Removed deprecated events
- Replaced GetHashKey with joaat
- Fixed all warnings using the lua language server
- Added oal
- Moved update player loop to server
- Moved paycheck loop to a thread because it's better
- Added compatibility for the getSharedObject export of es_extended
- You can now load all shared files without having them in order, because you didn't have to put them in order anyway, they don't use each other
- Made english only load if the language is actually english, if it's not set it'll be english anyway, so pre-loading it doesn't matter
- Removed all lower functions on strings, …
> Big untested core update because I was bored

- shared/locale.lua
Reverting this change because it broke things because lua
> fix(shared/locale): formatting

- server/functions.lua
Listen to when permissions update
> feat(server/functions): OnPermissionUpdate

- .github/workflows/assign.yml
This allows us to "take" issues by commenting on them. Should just need to respond to a issue with "take" and then you'll be assigned the issue to show that you are working on it. This can also make it easier for people outside the Org to see what's being worked on, and then allow them to even take issues without someone assigning them.
This is potentially a very useful CI change that could help us in the future.
> (feat) Automatic Issue Assignment on Reply

- config.lua
- server/player.lua
Extracted repeated code to do with id creation (as well as phone number and all that bs) in order to cut down repeated code. Reduced several functions to one as well as providing a better way create new identifiers by modifying the config.
> (Refactor) Extracted Unique ID Functions

- server/player.lua
It wasn't pointing to the table in the config
- [ x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ x ] My code fits the style guidelines.
- [ x ] My PR fits the contribution guidelines.
> (fix)server/player.lua: Generate Unique identifier

- client/functions.lua
It changes two of the qb-core functions to the ox_lib version.
> Overextended functions

- client/drawtext.lua
move drawtext to ox_lib
- [x ] My code fits the style guidelines.
- [x ] My PR fits the contribution guidelines.
> move drawtext to OX

- fxmanifest.lua
Forgot to add the newly created storage.lua to the fxmanifest
> fix(manifest): adding storage.lua

- server/player.lua
MUST DOWNLOAD THIS BRANCH IMMEDIETELY! OR THIS CAN BE VERY BAD!!!!!!!!!!!!!!!!
> FIX(MAJOR): SUPER HUGE TYPO (GAMECHANGER)

- config.lua
- server/storage.lua
- initial pass to define what a PlayerEntity is. Based off code analysis. Still some fields which I wasn't able to figure out the type for.
> docs(server/storage): more specific PlayerEntity contract

- client/events.lua
- client/functions.lua
- client/loops.lua
Converted more functions to use ox_lib and generally did some cleanup.
> Client: Ox Lib conversions and Cleanup

- server/player.lua
> fix(server/player): passing playerData to correct var name

- client/functions.lua
Fixes an error on startup because there are no vehicles around
> fix(client/functions): nil value on vehicleCoords

- client/functions.lua
Fixes https://github.com/Qbox-project/qb-smallresources/issues/18
> fix(client/functions): playerCoords nil value and cleanup

- client/drawtext.lua
fix drawtext export for qb-core
> compat(drawtext) compat with qb-core

- client/functions.lua
Removes the need for the old progressbar resource and uses ox_lib progressbar very cool
> Utilize ox_lib progressbar

- server/events.lua
- server/exports.lua
- server/functions.lua
- server/player.lua
Now everything prioritizes license2, but if it's not present it uses the normal license
> License fixes

- .github/contributing.md
- README.md
- client/drawtext.lua
- client/functions.lua
- fxmanifest.lua
- locale/ro.lua
- server/debug.lua
> Qbox'ing - stage 1

- config.lua
- server/player.lua
- server/storage.lua
- some minor refactors for readability improvements
- function annotations
> refactor(server/player): function annotations

- server/functions.lua
- server/player.lua
Working on better documentation so we can make the API easier to use & understand
> chore(server/functions): improved annotations

- client/drawtext.lua
- client/events.lua
> chore(client): replaced some deprecated calls and added more annotations

- client/functions.lua
- server/debug.lua
- shared/main.lua
- more annotations
- more code simplification
- optimizing GetPeds() to O(n) runtime instead of O(n^2)
> refactor: simplification and annotations

- shared/main.lua
- to replace duplicate code in qbx-management and qbx-vehicleshop
> feat(shared/main): add CommaValue shared function

- server/functions.lua
Add GetPlate to server, weird we didn't have this before
> feat(server/functions): GetPlate

- locale/bg.lua
Add the new locales to the Bulgarian locale.
> chore(bg): add new locales

- server/loops.lua
Use cron instead of while loop for saving players data and paychecks
> Use cron instead of while loop

- import.lua
Adds the ability to specify a resource name with the module loading
> feat(import): resource name

- import.lua
> fix(import): allow resource without side

- .github/workflows/assign.yml
- client/functions.lua
- modules/utils.lua
- server/functions.lua
Fixes `workflows/assign.yml` and some lint issues.
> fix: assign workflow and some lint issues

- server/player.lua
- update player health and armor on save
> feat: update player health and armor on save

- modules/utils.lua
- Fixes checking for extras
- Resets extras if found
- Applies extras properly
> fix(modules/utils): ChangeVehicleExtra stack overflow

- server/commands.lua
> flex tape /me

- server/events.lua
Chat are you even checking my code anymore
> fix(server/events): use correct variable

- server/player.lua
- Save metadata to DB on change
> fix(server/player): save metadata to DB on change

- modules/utils.lua
> chore(modules/utils): typo in func name

- server/player.lua
- server/storage.lua
- Adding id metadata for id_card on qbx-cityhall
> fix(server/player): fix licenses

- config.lua
- server/storage.lua
> support for differently named identifier columns

- locale/de.lua
> chore(locales): update de.lua

- server/player.lua
- also sneaking in deprecation tags for inventory functions which don't have an ox_inventory implementation
> chore(server/player): lowercasing local vars

- config.lua
- server/main.lua
- also sneaking in fix for require players path
> refactor: QBConfig into a module

- bridge/qb/client/main.lua
- bridge/qb/server/functions.lua
- bridge/qb/server/main.lua
- CreateQbExport is being invoked before it is loaded. Moved to the functions file
> fix(bridge/qb): export function load order

- client/main.lua
- modules/core.lua
- modules/playerdata.lua
- server/main.lua
Fixes core object errors, not using the module
> Fix module

- client/character.lua
This fixes a character delete on cancel issue from the latest commit 4d70bf3
> fix: confirm to delete char

- client/character.lua
- server/character.lua
- server/storage.lua
getting active skin & random ped instead of random clothes & gang information to character infos & reorder character information
> minor changes on character selection screen

- locale/cs.lua
new locales for Czech (thanks stepan_valic on discord)
> update(locale): czech

- server/loops.lua
> correct exports

- server/functions.lua
> Fix toggleOptin

- server/loops.lua
- added guard clauses
- extracted function
- added check that account exist as well as not be 0. I was seeing an error during testing that accounts weren't always numbers
> refactor(server/loops): re-organized paycheck cron using guard clauses

- bridge/qb/server/functions.lua
This is something QB does https://github.com/qbcore-framework/qb-core/blob/main/server/functions.lua#L265
> fix(bridge/qb/server/functions): wait for vehicle owner to be player

- bridge/qb/client/functions.lua
- client/character.lua
- config.lua
- modules/utils.lua
Waiting time for ox_lib to load the models before throws an error, for low specs pc
should fix https://github.com/Qbox-project/qbx_core/issues/219
- [✔] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [✔] My code fits the style guidelines.
- [✔] My PR fits the contribution guidelines.
> adding LoadingModelsTimeout

- bridge/qb/client/events.lua
- bridge/qb/server/events.lua
This seems to fix the errors of #230
> fix(bridge/qb): QBCore:Client:VehicleInfo passes netId back to the client

- server/main.lua
> Feat(lockdown): Use inactive lockdown mode as default.

- config.lua
- server/commands.lua
> feat: specify give vehicle key function via Config

- client/character.lua
Reverts Qbox-project/qbx_core#248
This hid the player from themselves
> Revert "fix: seeing/hearing other players in multichar"

- client/character.lua
- client/discord.lua
- client/functions.lua
- client/loops.lua
- client/main.lua
- config/client.lua
- config/server.lua
- config/shared.lua
- server/character.lua
- server/commands.lua
- server/events.lua
- server/functions.lua
- server/loops.lua
- server/player.lua
- server/storage.lua
camelCase the config variables
> fix: camelCase config variables

- bridge/qb/client/functions.lua
- bridge/qb/server/functions.lua
Bypasses ox_lib check that entity owner is the caller and attempts to set vehicle properties anyway. Displays a warning when this happens
> WIP: fix(bridge/qb/client/functions): best effort vehicle property setter

- README.md
Adds a read me with additional information and a super nice picture.
N/A
> Updated Read Me for Core

- bridge/qb/client/events.lua
- config/client.lua
- config/server.lua
- server/loops.lua
Removes dependencies as core needs to be nondependent on other resources.
> fix: remove dependencies

- config/server.lua
- server/character.lua
- server/commands.lua
- server/events.lua
- server/functions.lua
- server/player.lua
Replaces calls to legacy qb-log with logger module. Utilizes GetInvokingResource() to help identify the calling resource for logs.
> refactor: use logger module

- README.md
> fix: readme image

- config/server.lua
Set `checkDuplicateLicense` back to `true` because chat forgot to in 3dfc353.
> fix(config/server): default `checkDuplicateLicense` back to `true`

- client/loops.lua
Moved vehicletext from smallresources (& improved it too)
> feat(loops): Add addon vehicle names

- client/loops.lua
- client/main.lua
Manason said nuh huh to loops.lua :sad:
> move loop to main.lua

- fxmanifest.lua
Required onesync and FiveM Server Artifact 7290
> feat(manifest): require artifact 7290 and onesync

- config/server.lua
Replaces the old qbx_management money exports with the proper Renewed-Banking exports
> fix(config): replace old management exports

- client/main.lua
Use vehicle hash directly vice calculating the hash
> refactor: use vehicle hash directly

- client/main.lua
> vehicletext v6.9

- modules/utils.lua
Deprecates everything from utils, and refactors functions to utilize the lib module internally when possible.
A future PR will refactor the whole codebase to actually use the lib module.
Closes #301.
> refactor(modules): deprecate utils

- shared/jobs.lua
Allows multiple real estate agencies.
> Use type for realestate

- bridge/qb/server/main.lua
> fix(bridge/qb/server): SpawnVehicle & CreateVehicle callbacks

- server/player.lua
might be interesting to know who's metadata has been changed 🙄
> fix: send player source to server event

- server/groups.lua
- server/storage/groups.lua
Exports for creating/updating/deleting groups and grades
- Removed insert ignore storage functions as they are unused and there is no plan to use them
> feat(server/groups): new group modification exports

- server/groups.lua
Fixes #360 
Fetch group data after loading the rest of the file
> fix(server/groups): load functions before fetching data

- server/player.lua
Extracting a function for duplicate code
> refactor(server/player): helper function for creating a PlayerJob

- server/player.lua
The player will never have the unemployed job or none gang.
> fix(server/player): don't require player to have unemployed job/gang to be set as primary

- server/player.lua
Player has no existing job/gang during character creation.
> fix(server/player): handle no previous job/gang

- server/character.lua
- server/player.lua
Removes LoginV2 in favor of a single Login function
> tweak(server): remove loginv2

- server/storage/players.lua
Prepare was caching SQL statements that should have been dynamically generated
> fix(storage): replace using of prepare with single

- qbx_core.sql
- server/storage/players.lua
> fix: lastLoggedOut to snake case

- client/groups.lua
- Adds these exports to the client as well. They are already server exports.
> feat(client/groups): GetJob & GetGang export

- modules/lib.lua
- server/player.lua
Fixes #400 
- Adds qbx.table.size() to lib
- Failing linter until https://github.com/iLLeniumStudios/fivem-lua-lint-action/pull/15 is merged
> fix: max jobs/gangs enforcement

- bridge/qb/client/functions.lua
- bridge/qb/server/commands.lua
- bridge/qb/server/debug.lua
- bridge/qb/server/functions.lua
- bridge/qb/server/player.lua
- client/events.lua
- client/functions.lua
- client/main.lua
- config/server.lua
- modules/logger.lua
- modules/utils.lua
- server/commands.lua
- server/events.lua
- server/functions.lua
- server/groups.lua
- server/player.lua
- server/storage/players.lua
We already do this everywhere else. I just haven't gotten around to doing this for core yet until now
> refactor: standardize the usage of single quotes

- qbx_core.sql
- Untested, will test this before merging.
- Moving the two new additions (new column & citizenid collation change) to its own statement. This makes the sql file work for those upgrading their db
> refactor(sql): works for upgrading from QB in addition to fresh installs

- locales/lt.json
- Translated into Lithuanian language
> Lithuanian language fully translated lt.json

- config/server.lua
- server/commands.lua
Some key scripts look for vehicle entities and others look for plate numbers. This change offers flexibility for both systems.
> refactor: pass vehicle entity to giveVehicleKeys function

- client/loops.lua
> fix: RazerGhost

- locales/lv.json
Translated the lv.json into Latvian.
Note: Translated by a Latvian (me)
- [X ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [X ] My pull request fits the contribution guidelines & code conventions.
> Translate lv.json

- locales/pt-br.json
> Translate to pt-br

- bridge/qb/server/commands.lua
> fix(bridge/qb): maintaining param order of the callback

- bridge/qb/client/functions.lua
- config/server.lua
- modules/hooks.lua
- server/main.lua
- server/player.lua
- server/storage/players.lua
Makes things a bit more succinct and readable
> refactor: replaced if error statements with assertions

- bridge/qb/server/player.lua
> Added deprecated QBCore:CreateCitizenId compatibility to bridge

- client/character.lua
- server/character.lua
> refactor(character): Remove callback and use tutorial native.

- bridge/qb/shared/main.lua
Sorts out #393 
Needs tested first
> feat(bridge/shared): QBCore.Shared.StarterItems compat

- modules/logger.lua
https://overextended.dev/ox_lib/Modules/Logger/Server#fivemanage
> added fivemanage

- locales/sv.json
Improved existing translations and completed the unfinished ones.
> chore(locales): Update Swedish Translation

- locales/fi.json
Adds the missing translations for the finnish translation for qbx_core
> Update Finnish Translation

- server/storage/players.lua
This fixed broken built-in character select / deletion, since it's missing `citizenid` in returned data.
> fix(storage): add missing column in entities query

- client/character.lua
spawnDefault() already triggers this event so this is a duplicate trigger. This removes that.
> fix(client/character): remove duplicate event trigger

- server/functions.lua
Fixes an issue introduced in #519 where function catches when checking for a player without license2
> fix(server/functions): ban checking when no license2

- server/functions.lua
- server/storage/players.lua
Adds GetGroupMembers export from qbx_management to allow resources to fetch all the members of a group
> feat(server/functions): GetGroupMembers export

- server/player.lua
Screwed up the logic on this one. Someone could pass something invalid to grade and it would fail rather than returning grade 0
> fix(server/player): convert grade to number

- server/player.lua
Fixes `AddItem` and `RemoveItem` compat and adds a missing param
> fix(server/player): AddItem

- server/main.lua
v2.42.0 has some qbx bridge bugs
> chore: require ox_inventory v2.42.1

- server/main.lua
> chore: fix misleading dependency error

- modules/lib.lua
Uses iterative for loop for better performance compared to ox_lib's table.contains
> feat(modules/lib): qbx.array.contains to check if an array contains a given value

- locales/ja.json
- I added japanese translation.
> chore: add new locale [ ja ]

- fxmanifest.lua
Removed the extra `version` metadata added by the release actions
> fix(manifest): remove extra version metadata

- .github/workflows/lint.yml
- server/functions.lua
- server/storage/players.lua
- types.lua
Added the SearchPlayers export, which enables developers to access PlayerData for players in the database without needing their specific identifier and gives more flexibility to developers for advanced systems. The function has filters, so it doesn't dump a bunch of SQL data that is not needed.
> feat(server/functions): added SearchPlayers export

- locales/cn.json
Updated Chinese Simplified translations.
> chore(locales): Update cn translations

- qbx_core.sql
- server/events.lua
- server/player.lua
- server/storage/players.lua
- types.lua
We currently do not populate the players table with the appropriate userId like how we want to. This PR does that
> feat(server): add userId to players table

- server/player.lua
Fixes a typo which has been present for 9 months I guess
> fix(server/player): typo

- shared/vehicles.lua
- Adds vehicle types to all vehicles
- Adds missing manufacturers/brands on some vehicles
- Fixes some jumbled up vehicle entries
> feat(shared/vehicles): vehicle types

- server/functions.lua
- Adds `GetUserId` to be able to look up userIds
- Adds `GetPlayerByUserId` to be able to look up a player by their userId
> feat(server/functions): GetUserId and GetPlayerByUserId

- client/main.lua
Adds the same overloads to the client functions as in the server functions
> feat(client/main): getter param overloads to match server

- server/player.lua
Had someone test this but received no response on if it fixed their issue or not. I assume it did though.
> fix(server/player): erroring out after license

- server/player.lua
Fixes visual issues introduced by myself in the player functions deprecation commit.
> fix(server/player): money function visual regressions

- server/motd.lua
Fixes the wording to sync up with the changes in https://github.com/Qbox-project/txAdminRecipe/pull/118
> fix(server/motd): wording

- client/character.lua
I don't believe any of this has any effects on Qbox. These appear to just be old events.
> feat(client/character): remove spawn code

- client/character.lua
Reverts Qbox-project/qbx_core#648
Restores compat stuff
> Revert "feat(client/character): remove spawn code"

- server/events.lua
> fix(server): Ban Checking

- client/events.lua
These events are not intended to be triggered by clients.
> fix(client/events): secure client events

- client/main.lua
Updated the warning message format in the code to use string formatting.
> Warning Message Formatting in Vehicle Model Check

- server/groups.lua
> fix(server/groups): typo
