locale/en.lua, server/events.lua
Remove unneeded `Wait()` calls that made connecting to the server take longer.
Refactor code order to have deferral messages actually represent what happens in the code.
Catch and handle database errors and database timing out.
Originally PR'd as qbcore-framework/qb-core#844
=> feat(events/playerConnecting): accurate messages and handle db errors

shared/locale.lua
Fix Locale instances not actually being created.
After qbcore-framework/qb-core#693, calling `Locale:new` would not actually create a new table for the Locale instance but instead use the already existing `Locale` variable itself, which would result in running the following code:
```lua
setmetatable(Locale, Locale)
```
This would cause an error when trying to index the table with keys that don't exist in `Locale`.
With the intended way that `Locale` is used, this PR should work fine and be backwards compatible.
=> fix: locale instances not actually being created

client/functions.lua
It adds color types to core functions, so other resources could utilize it and expand vehicle color options.
=> Add color types to the vehicle props functions

server/events.lua
Needs feedback & testing, maybe it doesn't work and/or maybe there's a better solution.
Fixes QBCore issue qbcore-framework/qb-core#823
=> feat(server): check duplicate licenses on player joining

client/events.lua, server/events.lua
Now I can check isLoggedIn on the server as well
=> Handle isLoggedIn on the server instead of the client

client/functions.lua
QBCore.Functions.HasItems just returned back a boolean from qb-inventory. ox_inventory has something very similar, but does not return back a boolean - it returns back a table with k/v pairs with the item and the count that the player has.
This refactor calls the ox_inventory export, and does the logic to determine whether or not it's a table or a single string to check against. This allows you to:
1. Specify a string: `QBCore.Functions.HasItem('drill', 1)`
2. Specify a table with 1 item: `QBCore.Functions.HasItem({'drill'}, 1)`
3. Specify a table with many items: `QBCore.Functions.HasItem({'drill', 'water_bottle'}, 1)`
This allows us to maintain existing functionality for escrowed scripts that use this function.
=> refactor(client): HasItem: use ox_inventory export

client/events.lua, server/commands.lua
Optimized the me command that is used frequently in servers, this change gets rid of stupid server side distance checks and uses statebags.
=> Use statebags for me command

config.lua, server/exports.lua, server/functions.lua, server/player.lua, server/storage.lua
Introduces a storage layer to abstract away the database schema behind a defined storage API. This allows us to change either the API or the schema without making a breaking change to the other. Right now the API is largely 1:1 with the schema, but that will soon change as the schema diverges.
- made all storage functions synchronous. Calling them from threads to maintain async functionality in the code where it existed before.
- Code now assumes that all bans will have at least one of three identifiers: license, discordId, or ip
=> feat(server)!: add storage layer

client/events.lua, client/functions.lua, server/events.lua, server/exports.lua, server/functions.lua, shared/gangs.lua, shared/items.lua, shared/jobs.lua
- more annotations added mostly in server/exports
- minor refactor in server/exports
- added prints to all deprecated functions/events to make it easier to replace deprecated calls
=> refactor(server): more annotations, minor refactors

client/events.lua, client/functions.lua, client/utils.lua, fxmanifest.lua, server/commands.lua, server/events.lua, server/functions.lua
- deprecating QB callbacks for creating/spawning vehicle in favor of new ox_lib callbacks
- deprecating vehicle creation functions/callbacks on the server which use CreateVehicle native rather than CreateVehicleServerSetter. Existing functions/callbacks are now wrappers.
- BREAKING CHANGE: 'QBCore:Server:CreateVehicle' server callback will now return nil rather than 0 if the server artifact is below 5904. This brings the behavior in-line with the function version.
- server events/functions which spawn vehicle refactored to call the server to spawn the vehicle
- BREAKING CHANGE: QBCore.Functions.CreateVehicle server function now returning the netId instead of the entityId. I'm too sure about whether this is a good change or not, but it seemed odd that the original callback returned the …
=> feat(server)!: Vehicle Spawning Overhaul

server/functions.lua
- Did some testing with the native and found that the loop waiting for it to exist never runs any iterations and that a single frame wait is needed prior to teleporting player into vehicle.
=> fix(server/functions): fix teleporting player into vehicle on spawn

shared/vehicles.lua
Remove shop from qbx-core as vehicle to shop mapping source of truth should be qbx-vehicleshops. To be merged after https://github.com/Qbox-project/qbx-vehicleshop/pull/20
=> feat(shared/vehicles)!: remove shop

client/events.lua, server/functions.lua
Giving keys and deleting current vehicle changed from client side state bag handler to now being done in the server side function to spawn vehicle. This fixes an issue where the network owner of the car was assumed to be the framework owner of the car; when in fact the two are completely different concepts.
=> fix: setting vehicle owner incorrectly on spawn

server/player.lua
- A lot of other scripts listen to the toggle duty events instead of getting the whole playerdata object to get the latest duty status.
=> Add Toggle Duty events when duty is changed.

server/commands.lua
The following PR prevents an error when a resource calls QBCore.Commands.Refresh function since it doesn't exist in the core. This "fix" was suggested by Manason on Discord, I just took time to test it out and make sure it works.
I hope you guys are satisfied with the print :D
=> Prevent error when calling function

modules/utils.lua
- removed code in SpawnVehicle which deletes the vehicle the player is currently in. This assumption is a side effect of spawning a vehicle and isn't always desired. If deleting a user's current vehicle is preferred, that should be done before calling spawn vehicle
- cleaned up some duplicate code getting the player's ped
=> feat(modules/utils): spawn vehicle no longer deletes current vehicle

server/events.lua
If whitelist is enabled, the call to `IsWhitelisted` which follows `IsPlayerBanned` essentially overwrites the latter function's error, if one occurred.
=> fix(server/events): `IsPlayerBanned` errors being ignored

locale/bg.lua, locale/da.lua, locale/en.lua, server/events.lua
Rephrases anything related to errors occurring when connecting to a server, since a general error can occur there rather than strictly a database-related one.
Replaces `connecting_database_error` with `connecting_error` completely since the former will lose meaning in all locales.
=> refactor(server/events): use wording for a general error

server/commands.lua
Teleporting by id doesnt work.
do /tp 1 with someone else in the server and it will not permit user to get to them
Here is the bug report i got from my server community:
```we type /tp 3 while id 3 is online and it will say "Location Does Not Exist".```
=> bugfix(qbx-core/sv): fix teleporting by id

client/functions.lua, modules/utils.lua, server/functions.lua
- Make server side QBCore.Functions.HasItem call the HasItem function from utility module
- Deprecate all HasItem functions in core in favor of direct ox_inventory calls. We shouldn't provide a wrapper for inventory calls unless we plan to support other inventory resources.
=> refactor: server HasItem and deprecation

server/main.lua
- Can be overridden via convar. Didn't add to QBConfig as we should move towards Convars for cross script configuration
- This could and most likely will cause insecure resources to break
=> feat: prevent clients from creating networked entities

server/player.lua
Prevents saving the position when inside of a property/apartment, (make sure to save player before entering ofc)
=> Player save position (properties)

.vscode/settings.json, server/functions.lua
- instead of ExecuteCommand directly to make the code a bit cleaner
- also snuck in deprecation of qb-inventory function UseItem
=> refactor(server/functions): using ox_lib acl

modules/utils.lua
As this was introduced 3 months ago, I don't suspect it has any users and therefore should be likely safe to remove in favor of the new ox_lib waitFor function
=> chore(modules/utils): Remove WaitFor in favor of ox_lib

client/functions.lua, server/functions.lua
This keeps UI consistency between ox_inventory and previous notifications, since this text is/was not bold respectively.
=> fix(functions): use text as description when no subTitle specified

client/character.lua
Currently you will skip the character selection process because lib.checkDependency() doesn't find ox_lib as 'overextended/ox_lib' - the version returned is 'unknown'. This was hard to track down because the print was disabled.
=> Update resource argument and enable print bool

modules/utils.lua
I believe this does not work from the modules, I can't say the reason exactly, I see that modules are loaded as files. But it appears that on the modules, the spawnvehicle function, will not provide the keys. I was able to get the duplicate message from this function that keys were given plus the code on the client side. If I NetToVeh the NetId of this vehicle and then on the client side apply the keys, it will work correctly.
=> fix(utils): remove give keys on server side vehicle creation

client/main.lua, server/loops.lua, server/main.lua, shared/gangs.lua, shared/items.lua, shared/jobs.lua, shared/locations.lua, shared/main.lua, shared/vehicles.lua, shared/weapons.lua
It strikes me a bit strange that we have a QBShared global that is mutated across several different files. This PR uses ox_lib require to build up the QBShared table and therefore create some Immutability for it. This also gives up deterministic file execution order, as well as reducing code scope.
=> refactor: creating QBCore.Shared table in a module

bridge/qb/server/functions.lua
Apparently within a module, even global functions need to come first
=> fix(bridge/qb/functions): global function within a module needs to come first

client/character.lua, client/events.lua, modules/playerdata.lua, server/character.lua, server/player.lua
- refactoring character creation flow to convert events to functions where possible and limit net events
- setting PlayerData in module to ensure PlayerData is set before the OnPlayerLoaded event is triggered. I moved the events that trigger setting of PlayerData to come before the event for OnPlayerLoaded. In theory I think this still means that OnPlayerLoaded handlers could handle the event before PlayerData has been set, but this should make it less likely. Since this is an improvement, will leave it as is, but having the PlayerData guaranteed before the OnPlayerLoaded event is set would be the best solution.
=> refactor: character creation flow to set PlayerData

client/character.lua, client/events.lua, server/character.lua, server/player.lua
- Partial rollback of #166 
- Handling player loaded tasks via event again for those that disable core multi char
- setting core player data via event again for those that don't load the PlayerData module
- introducing playerObj.LoginV2 to return the player obj while reverting Login to be a boolean return for compatibility
=> fix: broken login compatibility

client/main.lua, modules/core.lua, modules/playerdata.lua
- Removes exports['qbx-core']:GetCoreObject() as people should just be using the module
- exports['qb-core']:GetCoreObject() will continue to work for those needing backwards compatibility and can be used at the same time as a module to switch a resource over gradually off of the qb core object
- Also renaming the global variable supplied by the module to 'QbxCore' so that resources that currently contain QBCore variables won't have a conflict, and both can be used at the same time. The rename also helps communicate that QbxCore does not contain the same functions that QBCore does.
=> chore: remove qbx-core GetCoreObject export in favor of module

client/character.lua, locale/en.lua
Adds confirmation when deleting characters using the core character selection. Returns to previous context menu if choosing cancel.
Closes #186
=> feat: Confirm to delete character

client/main.lua, modules/utils.lua, server/main.lua
Adds an export that returns a mapped table of shared/vehicles.lua by category.
Answers #183 
will return all the biccyles, one example in this table:
```lua
{
"brand": "Bike",
"category": "cycles",
"hash": -400295096,
"model": "tribike3",
"name": "Tri Bike 3",
"price": 520,
"shop": "pdm"
}
```
=> Add GetVehiclesByCategory() Export

client/main.lua, server/player.lua
Fixes #207 
When saving a player, the source of truth for health and armor is the ped itself. Loading an existing character was triggering a save, which overwrote health and armor in the database with default ped values (full health, no armor). This save now only occurs for new character creation as saving the same character data that was just loaded has no purpose.
Additionally, setting the ped health & armor when playerdata is loaded to avoid reliance on any other resources to persist this from the database to the ped. Unfortunately there is no server side native for setting health, so a callback was used.
=> fix: save health & armor properly

bridge/qb/server/functions.lua
- Qbox changed the spawn vehicle function to return netId instead of entityId. The bridge now correctly returns entityId instead of netId for qb compatibility.
=> fix(bridge/qb/server/functions): spawn vehicle returns entityId

bridge/qb/server/functions.lua
- This was calling the native GetPlayers previously which has a different behavior than QBCore's GetPlayers. It has now been fixed to return an array of playerIds for players that are logged in.
=> fix(bridge/qb/server/functions): GetPlayers()

server/character.lua
- Investigated reports of players spawning in and not being able to see each other (being in different buckets)
- Observed that SetPlayerRoutingBucket doesn't seem to be consistently working. Sometimes it sets the routing bucket and other times it doesn't. It seemed to only work when multiple players connected at the same time, but this might just be a coincidence. When this actually worked to set the bucket to the player source, the second call to SetPlayerRoutingBucket to 0 had no effect. Unsure why this is, but best guess is that there is something broken about SetPlayerRoutingBucket native.
- Removed code setting the player's bucket to source. This has the effect of player's being able to see each other when in the same character selection location. However, this is preferable to …
=> fix(server/character): spawning players in different buckets

client/events.lua
Setting player logged in statebag on the client. This is what QB does. #228 is due to a race condition which checks the statebag before it's been replicated from the server to the client. While this race condition in theory still exists, this reduces the latency to the point that in practice it works. The ideal future solution is to set this before the onPlayerLoad event is triggered.
=> fix(client/events): set player logged in statebag on client

bridge/qb/client/events.lua, bridge/qb/client/functions.lua, modules/utils.lua
- wait for onesync to pick an owner before returning from the spawn function
- convert get/set properties between qb and ox versions within the bridge
=> fix: vehicle spawning

bridge/qb/client/functions.lua, client/events.lua, modules/utils.lua
- switched from using a statebag event handler to using a normal event. This seems to fix the rare entity not exist issue when spawning a vehicle
- tested and fixed some bugs regarding vehicle property bridge compatibility to set/get vehicle properties using bridge
=> fix: vehicle prop bridge compat & vehicle spawn entity not existing

client/events.lua, modules/utils.lua
- Add props to SpawnVehicle function to pass this through to the entity owner. Only the entity owner can set vehicle properties so it makes sense to do this on spawn
- Remove previous default values (fuel, dirt, radio, hotwire status). We'll add them back as needed/desired.
=> feat: set vehicle properties on vehicle spawn & removed other default properties

bridge/qb/server/functions.lua, modules/utils.lua
- needed to avoid incompatibilities with server side vehicle spawning and QB
- changed inputs and return of CreateVehicle to match QB
- made props an optional field when spawning vehicle in utils (forgot to do so last PR)
=> fix: bridge SpawnVehicle uses CreateVehicle

client/discord.lua, client/loops.lua, client/main.lua, config.lua, fxmanifest.lua
Adds the Discord Rich Presence settings from qbx_smallresources and the ability to customize your pause menu text. By default, it is set to "Powered by Qbox".
=> feat: drp and pause menu text

server/character.lua, server/commands.lua, server/events.lua, server/loops.lua
Update the core server side files to use the Notify function instead of the old QBCore:Notify event
=> fix: switch to notify function

client/character.lua, fxmanifest.lua
- Minor manifest edit to add the repository link
- Removed the capitalized string check in favor of automatically capitalizing it on creation. (It takes the string, takes each word, and capitalizes the first letter automatically while leaving the rest lowercase.) This should take care of a portion of #197
=> fix: auto-capitalize

client/character.lua
Hopefully fixes seeing/hearing other players in multichar as stated in #226
=> fix: seeing/hearing other players in multichar

bridge/qb/client/drawtext.lua, bridge/qb/client/main.lua, bridge/qb/server/functions.lua, bridge/qb/server/main.lua, bridge/qb/shared/export-function.lua, fxmanifest.lua
Can put` setr "qbx:enablebridge"` false into server.cfg to disable the bridge entirely. Useful if you aren't using the bridge to avoid extra overhead.
To accomplish this, modularized all the bridge files, so that the only loaded file via fxmanfiest is main.lua on client and server
=> feat: toggle bridge on/off via convar

modules/utils.lua
Beforehand it was returning lib.waitFor without even checking if the networkId exsist (which was the entire reason for lib.waitFor). Due to this we had multiple errors when statebags was still used, meaning theoritically we could swap back.
=> fix(statebags): wait for entity ID to exsist in network

fxmanifest.lua
Files inside of the manifest means that clients can read these files through dumping files etc.
WE DO NOT WANT THAT, the reason it was most likely put here was when we swapped to modular loading, but server files do not need to be loaded this way.
=> feat(manifest): remove client readability

client/character.lua, config/client.lua
Fix new character spawning when not using qbx_spawn and renable starting apartments after it was mistakenly disabled.
=> fix: new character spawning

client/character.lua
Fixes a typo in "qbx-apartments" it should be "qbx_apartments" ;)
=> fix(character): typo

config/client.lua
On a fresh install, you get "No such export HasKeys in resource qb-vehiclekeys" whenever you sit in the vehicle. I guess this was a typo in the last commit, so this fixes that problem.
=> fix: typo for haskeys export

shared/gangs.lua, shared/jobs.lua
Fixes not being able to see society funds for jobs or gangs when using Renewed-Banking
=> fix: missing bankAuth for society banking

modules/logger.lua
Discord webhooks support changing the hook username and avatar_url. This adds the variables to change the name of the webhook . This replaces the Captain Hook and default avatar with the configured variables.
=> feat: add logging avatar

server/events.lua
In the `playerConnecting` event, use `GetPlayerIdentifierByType` instead of looping over `GetPlayerIdentifiers` to guarantee using `license2` over `license` when available.
=> fix(server/events): fix license sometimes being used instead of license2

bridge/qb/server/main.lua
There is no list field of the commands table. I believe if you attempt to Execute a command that doesn't exist you will get an error or a no-op anyway, so the gate condition doesn't seem needed.
=> fix(bridge/qb/main): QBCore:CallCommand event

locale/en.lua, server/events.lua, server/queue.lua
Adds a bare-bones in-house queue system.
See #279 for additional context.
=> feat: in-house queue system

client/discord.lua, config/client.lua
Basically just adding a config toggle (enabled by default to simulate previous implementation) to the discord rich presence.
=> feat(discord): add toggle for rich presence

config/queue.lua, locale/en.lua, server/queue.lua
Adds sub-queues/priority queues, adding easy configuration for adding predicates determining whether players belong in them.
See #279 for additional context.
=> feat(queue): sub-queues

config/queue.lua, locale/en.lua, server/queue.lua
Adds an updating adaptive card that shows the progress of the player in queue from start to finish.
Since the adaptive card has a time display this adds it to the locale message too.
See #279 for additional context.
With this PR the initial queue implementation is finished.
Preview:
=> feat(queue): adaptive card & display time

bridge/qb/client/functions.lua
Fixes the parameters for `QBCore.Functions.DrawText` and `QBCore.Functions.DrawText3D`.
See `qb-core/client/functions.lua` [line 21](https://github.com/qbcore-framework/qb-core/blob/b132f2963ee01252eb08b1ed384ad797a7008ff1/client/functions.lua#L21) and [line 31](https://github.com/qbcore-framework/qb-core/blob/b132f2963ee01252eb08b1ed384ad797a7008ff1/client/functions.lua#L31)
=> fix(bridge/qb/functions): drawtext parameters

client/character.lua
Sets to third person view on server join/logout,
Prevents a weird behavior where the ped is facing the same way you're looking.
Like that:
(I think your view is persistent across servers too? so if you left in first you'll join in first?)
=> Set to third person

server/character.lua
This will allow for basic character creation to proceed even if ox_inventory is missing from the server.
=> modify: allow for basic character creation without ox_inventory

server/events.lua, server/queue.lua
Possibly fixes deferral hangs.
The [FiveM docs](https://docs.fivem.net/docs/scripting-reference/events/list/playerConnecting/) state that before using `deferrals.done` you must wait at least a tick before calling it after calling a prior deferral method, which we weren't doing. So I assume that may have caused the deferrals to just not go anywhere.
I have no way of reliably checking this but let's assume that it works ;)
=> fix(server/events): possibly fix deferral hangs

modules/lib.lua
Implements a new Qbox library as per #301.
All functions have been tested except for audio & statebag related functions.
Most functions have been refactored a bit, so the code should be reviewed.
Usage of the library and the deprecation of the utils module will come in following PRs.
- `GetCoordsFromEntity` => not carried over (feels useless)
- `GetPlate` => `qbx.getVehiclePlate` (removed a nil check)
- `CommaValue` => not carried over (`lib.math.groupdigits` exists in ox_lib)
- `string.split` => not carried over (`string.strsplit` exists in CfxLua 5.4)
- `string.trim` => `qbx.string.trim` (removed a nil check and an unneeded return value)
- `string.firstToUpper` => `qbx.string.capitalize` (ditto)
- `math.round` => `qbx.math.round`
- `RandomLetter` => not carried over (`lib.string.random` …
=> feat(modules): lib

modules/lib.lua
Most usages of the `SpawnVehicle` function from the utils module is done by passing the player and no coords, to spawn the vehicle at the player's ped and warp them inside.
This PR modifies the params to be able to support that, and `vector3` coords more easily.
Examples:
```lua
qbx.spawnVehicle({
model = `asbo`,
spawnSource = GetEntityCoords(ped),
warp = ped,
})
qbx.spawnVehicle({
model = `asbo`,
spawnSource = ped,
warp = true,
})
```
=> feat(modules/lib): support passing a ped instead of coords

client/events.lua, modules/lib.lua, modules/utils.lua
Fixes #316. The current code flow for spawning a vehicle server side relies on the entity owner (client) to set the vehicle props. Due to various sync issues triggering this via NetEvent is not recommended as it causes an early return to the SpawnVehicle function in the Utils and Lib modules. Depending on the code following the SpawnVehicle call another entity owner may be set before the first entity owner can make the changes to the vehicle props. This fix yields until the original vehicle prop set request is completed before returning the netId to the caller of SpawnVehicle
=> refactor: use callbacks instead of netevents for setting vehicle props

config/shared.lua, server/events.lua
Adds a shared config for server name to avoid using any special color coded values in the deferrals section (unsure if deferrals will honor those). My suspicion says it will look like `Welcome to ^3SUPER ^1LIT ^2RP`. Originally this was a fix for the issue corrected by #323 but David's had error handling so I held off until it was merged.
=> feat(server/events): use shared config string for server name

config/queue.lua
Refactors the queue config to get the server name from the config string added by #325 instead of the convars.
=> refactor(config/queue): use shared config string for server name

server/commands.lua
Lang:T used a table replace variables. Locale just uses a bunch of variables. This fixes an issue with gang and job commands
=> fix: locale error for gangs/jobs

modules/lib.lua
GetVehicleNumberPlateText has to be trimmed and you can't trim a nil. This fixes that
=> refactor: nil check for GetVehicleNumberPlateText

server/functions.lua
Adds support for inventory instances.
Check: https://github.com/overextended/ox_inventory/blob/8f565f8ca9cb55ea78eb9666c409363928f2f2ee/client.lua#L1088
Whenever you change routing bucket all drops should dissapear and this PR does exactly that.
another benefit that other scripts can now use this same information which is great 👍
=> Fix(bucket): Set player instance state whenever you change bucket

config/queue.lua
Fixes a nil error by actually making the sub-queue `cardOptions` optional. (this was supposed to be the expected functionality, whoops...)
=> fix(queue): subqueue card options not being optional

bridge/qb/client/functions.lua
Players are not vehicles... This corrects that issue.
=> fix: players are not vehicles

bridge/qb/client/functions.lua
v1.5.0 broke backwards compatibility by changing some function headers and behaviors. This restores the behavior to what it was prior to v1.5.0
=> fix(bridge/qb/client/functions): restore backwards compatibility

server/player.lua
SetMetaData now triggers a clientside event that can be listened to,
`AddEventHandler('qbx_core:client:onSetMetaData', key, oldValue, newValue)`
`AddEventHandler('qbx_core:server:onSetMetaData', key, oldValue, newValue)`
=> feat: onSetMetaData event

bridge/qb/client/functions.lua
Make the QB bridge functions more strict with backwards compatibility after the changes in #337.
In QBCore these functions do not accept an `ignoreList` param but currently we do: `GetVehicles`, `GetObjects`, `GetPlayers`, `GetClosestVehicle`, `GetClosestObject`
In QBCore this function does not accept a `maxDistance` param: `GetClosestPlayer`
In addition the `GetClosestPlayer` function was edited to not use ox_lib because it requires using a max radius.
=> fix(bridge/qb/client): make functions strictly backwards compatible

bridge/qb/client/functions.lua
Fixes an issue introduced by #338 where `GetClosestPlayer` wouldn't ignore the local player. In addition the original QBCore function only returns players in a 5-radius distance from the local player, this is now fixed too.
=> fix(bridge/qb/client): GetClosestPlayer not ignoring local player

modules/lib.lua
Lets you disable the drawRect which can be really ugly & not that necessary in some cases
=> feat: Add disableDrawRect param

qbx_core.sql
Moves groups from config into database. Config would be the default values and the database would override.
This allows for jobs/gangs to be modified at runtime supporting features such as players changing names.
Opted for a more flexible structure since normal use cases would be reading/writing to an individual group/grade. Querying a selection of grades/groups doesn't seem to be a likely use case.
=> feat(dynamic groups): sql schema

bridge/qb/server/functions.lua
bridge core object calls exports to modify groups instead of doing so within the localized core object. This will help setup these modification functions to read from core memory directly instead of core object cache memory, which is more likely to be stale with upcoming PRs.
=> refactor(bridge): modify groups in core instead of in the core object

fxmanifest.lua, server/groups.lua, server/storage/groups.lua
- On initial load, gangs/jobs are fetched from the database. Any groups in the config, but not in the database are added to the database. It's intended that server operators edit the database directly and stop using the job/gang config. Future PRs will make this easier by adding menus and commands to edit groups with.
=> feat: jobs/gangs stored in database instead of config

server/storage/groups.lua
`GROUP` is a reserved keyword, so it has to be escaped.
=> fix(server/storage/groups): escape `group` in queries

server/storage/groups.lua
The wrong variable was used to instantiate groups when fetching them.
=> fix(server/storage/groups): wrong variable used in group instantiation

qbx_core.sql
- Changed group tables to use varchar instead of enum. Would rather this be more flexible in case we want to add new enum values, don't need to modify the schema.
- Add new table player_groups to map characters to group_grades. Foreign key constraints enforce that a grade must exist for a player to hold it
=> feat(sql): new table player_groups for multi-job

server/player.lua
Now that jobs & gangs can be modified at runtime, those changes need to be propagated to the playerdata table for any players who hold those groups. To do this we're consuming group updated events, making the needed changes to playerdata, then triggering additional events for playerdata updates to propagate that to the client.
We do not need to remove the player in the case of a group/job/grade being deleted as the database constraints will guarantee that a player can never be in a group or grade that doesn't exist.
=> feat(server/player): update job/gang playerdata entries dynamically

fxmanifest.lua, server/character.lua, server/functions.lua, server/groups.lua, server/player.lua, server/storage/groups.lua, server/storage/main.lua, server/storage/players.lua
Mainly doing this to more easily distinguish storage functions from other functions.
- renamed a few functions where it made sense. Naming can be more broad since we now have a storage prefix to know that it's in the context of storage.
=> refactor(server): organize storage functions into a module instead of global functions

config/server.lua, server/player.lua, server/storage/players.lua, shared/gangs.lua, shared/jobs.lua
- Introduces new playerdata jobs & gangs tables to hold key value data of all the player's groups (name & grade), including the primary. The only exception is the unemployed/none groups so that these don't contribute to the player limit.
- The existing playerdata.job/gang is the primary group, and is populated with all the data about that group and grade.
- New exports added for managing player jobs/gangs (add, remove, set primary)
- To maintain backwards compatibility, SetJob & SetGang will replace the primary job rather than act as an alias for Add.
- New config options to limit the total number of jobs/gangs a single player may hold at a time
The multi-group system is not optional and cannot be disabled. While using external multigroup systems is still possible, unless they use the …
=> feat: multi job/group implementation

bridge/qb/client/main.lua, bridge/qb/server/main.lua, bridge/qb/shared/main.lua
Fixes an issue where the core didn't finish loading before other resources loaded. Doing a lib.callback.await doesn't block other resources from loading, but does block core. To get around this, the jobs/gangs tables of bridge are initialized to empty tables and then will be populated asynchronously once the lib callback returns. The event is then triggered to simulate as if these groups were added via export.
=> fix(bridge): core not loading

server/main.lua, server/queue.lua
Fixes the issue described in https://github.com/Qbox-project/qbx_core/issues/367#issuecomment-1946603716.
Bump ox_lib to a version that includes a fix for returning `false` from required modules (overextended/ox_lib#502), and return `false` from `queue.lua` when it's disabled (`events.lua` already detects when it returns a falsy value).
=> fix(server): error when disabling queue

server/player.lua
- General refactor to make the code more succinct.
- Removed unnecessary default param values
- Changed behavior of the functions to be no-op in the case of the group or grade not existing. Previously it would pick defaults instead, which seems like an undesirable behavior.
- Added error prints
- Changed removeFromJob/removeFromGang behavior when the user doesn't already have the job/gang to be no-op rather than an error scenario to make the function Idempotent. This is also useful because we don't treat the player as having the unemployed job or the none gang.
- Fixes an issue where instead of removing the old job/gang, it was attempting to remove the current one
- Prevent removing/adding to the default groups as the default groups are not tracked in the database.
=> fix(server/player): setgang and setjob error handling

server/player.lua, server/storage/main.lua
The only thing the stored playerdata.job and .gang will be used for now is the name, grade, and last onduty value. Other fields of job/gang will be derived from the job/gang data. This fixes the potential for stale cached data on the player object. This doesn't change what data is written to the database.
=> fix(server/player): use job/gang data as source of truth instead of playerdata

server/player.lua
lowercases the name of the group and defaults the grade to 0, making it an optional param. This restores the original function definition that qb-core had.
=> fix(server/player): default grade value for setjob/gang

server/player.lua, server/storage/players.lua
Adds a console command 'convertjobs': An idempotent function which copies all player's primary job & gang into the player_groups table. This works for both online & offline players, so isn't required to be ran when the server is empty.
We want the player_groups table to accurately reflect the groups the player is in. Without doing this step, it is likely that the data will eventually make its way into the player_groups table, but that would lessen the accuracy of exports that return data about which jobs the player holds. I also considered doing a check on player login instead, but that would preclude offline players from having their data corrected. The best solution I feel, is to convert all at once to guarantee the data is present immediately.
I didn't include conversions for existing …
=> feat: console command convertjobs

qbx_core.sql, server/events.lua, server/player.lua, server/storage/players.lua
Adds a new db column 'lastLoggedOut' that is updated on logout & playerDropped.
This new value can be accessed through the PlayerData & used to know when the player last logged out.
=> feat: lastLoggedOut in PlayerData

bridge/qb/server/main.lua, config/queue.lua, config/server.lua, server/commands.lua, server/events.lua, server/functions.lua
The abstraction built into qb on top of ACE permissions is confusing without adding value. Deprecated with the recommendation that developers use native ACE permissions + ox_lib to manage permissions.
=> chore(server): deprecate permissions in favor of cfg ACE

bridge/qb/server/functions.lua, bridge/qb/server/main.lua, bridge/qb/shared/export-function.lua, client/character.lua, client/discord.lua, config/server.lua, modules/utils.lua, server/character.lua, server/commands.lua, server/events.lua, server/functions.lua, server/player.lua
We currently have a mix of string.format, colon syntax formatting, and just normal concatenation. This just standardizes the colon syntax over the other usages.
=> refactor: format strings using colon syntax

server/player.lua
- Adds two new convars qbx:setjob_replace and qbx:setgang_replace
- These determine whether the player function SetJob & SetGang should replace your existing primary job/gang or not. They default to true, but some users may want to turn the replacement off.
=> feat: setjob replace convar

client/events.lua, modules/lib.lua
Vehicle props are sadly a client side thing. This change moves the logic from a callback to a statebag which runs a loop on any client within scope to set the props on a vehicle. Extensive testing has shown this is the best method of ensuring that if you ask for a blue car with a wing that you get a blue car with a wing no matter who is zipping by at 400mph or if your client/server is a potato.
Fixes #316
Credit @FjamZoo for the ox_core version of this
=> refactor: vehicle props as statebag

server/player.lua
When updating groups for a player we don't trigger any event that can be consumed to update other resources. This adds a new event for resources to listen to and perform various functions such as updating UIs etc.
=> feat: event on group updates

modules/lib.lua
Convert the lib module's `lib.drawText2d` and `lib.drawText3d` rgba values from vector4 float values to integers, since [`SetTextColour`](https://docs.fivem.net/natives/?_0xBE6B23FFA53FB442) only accepts integers.
=> fix(modules/lib): convert vector rgba values to integers in drawtext

modules/lib.lua
When warping a ped into a vehicle the vehicle props should already be set otherwise they may fail to set because of entity ownership changes. This moves the prop setting above warping the ped and yields until props are set.
Tested this with two folks with over 100ms latency to the server standing next to each other and props didn't fail to set at all. The wait is for up to 5000ms due to possible issues with streamed vehicles not loading for clients on slow links.
=> refactor: set props before ped warp

bridge/qb/server/events.lua, client/loops.lua, server/events.lua, server/loops.lua, server/player.lua
Statebags are cool :+1:
It keeps compatibility with the old way of setting those values, so we can start using statebags without anything being broken until then!
(please test to make sure i didn't fuck it up)
=> feat: use statebags for hunger/thirst/stress

modules/logger.lua
This pull request adds an additional field to the logger function for tagging logs to be sent to ox_lib for API POST requests.  This allows people to have finer log control by being able to assign their own KV pairs to their logs, further enabling searching and querying.  See [lib.logger](https://overextended.dev/ox_lib/Modules/Logger/Server#liblogger) documentation in regards to the `vararg`.
=> Add support for ox_lib Datadog and Grafana Loki logging

server/player.lua
Adds the missing `lib.` prefix to the math function added in the statebag pr
=> fix(server/player): add lib prefix to math function

config/server.lua
It adds a letter to the first character of the `citizenid`. This presents problems in some functions such as `GetPlayerByCitizenId(cid)`.
Statistically, this is an extreme edge case, but the RNG has dealt its cards among one of my players and this is the issue after further review. Maybe this would be better suited to enforce string conversion in the functions that accepts CID... but this at least stops the problem at the source.
=> config(server): add letter to citizen id generator

server/player.lua
statebags shouldn't be nil on logout but maybe if you got potatoes connected to potatoes then you'll be a nil bagholder
Statebags shouldn't be nil that fast on logout but in case they are don't zero the players metadata needs.
=> fix(server/player): do not zero metadata on logout

modules/lib.lua
When spawning vehicles serverside we need to create a temporary vehicle to get the vehicle type. For most vehicles this is okay but some can explode when being spawned at 0,0,0. this pushes the spawn under the map so that they don't go boom
=> fix(modules/lib): spawn temp vehicle under map

server/player.lua
Trying to set a statebag when the player is offline probably ain't gonna work. This moves these set events into a conditional that should correct issues with offline player data management
=> fix(server/player): only set state when possible

bridge/qb/server/commands.lua
Fixes bridge commands in cases where the arguments are not explicitly declared in the function. Observed in the wild that scripts were not declaring the help text, but still using the passed through arguments.
Fixes #437
=> fix(bridge): qb commands with implied arguments

client/character.lua, server/character.lua
This adds back in bucketing to internal multicharacter, creating a callback to change player bucket. Refactors the use of bucket native to use internal SetPlayerBucket function. Finally releases a model request not being released after use.
#226
=> refactor(client/server): Reintroduce Bucketing and Release streamingRequest

server/player.lua
Fix for default duty not working if set to false
=> Fix #443 - Fix for default duty not working if set to false

server/player.lua
=> fix(server/player): setting default duty after job exists

server/player.lua
This fixes an issue where the statebag statuses were clamped to 0-100 while the meta statuses wcould go over 100. causing them to become desynced. this would cause huds that use metadata values to say that players had more hunger/thirst than they really had and they would start dying for no apparent reason. it will now clamp both to 100.
repro here in issue #457 
- [x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ x] My pull request fits the contribution guidelines & code conventions.
=> fix(server/player): status desync

modules/lib.lua
Adds a function to get the vehicle mod name and vehicle livery name. Came across a use for it and realized we didn't have it in our lib so I figured I'd toss it in here. Not sure what everyone else's options on it are.
=> feat(modules/lib): getVehicleModName and getVehicleLiveryName

server/player.lua
Fix an issue where when firing a gang member, it doesn't fully fire them as reported in https://github.com/Qbox-project/qbx_management/issues/58
=> fix(server/player): removing player from gang

server/functions.lua, server/player.lua, server/storage/players.lua, types.lua
When the caller of an API function passes an illegal value (equivalent to a 4xx HTTP error), changing existing assertions to instead return success, errorResult to allow the caller to handle those errors or else fail silently. This is a departure from assertions, which require errors to be caught and handled or else blow up the stack. The thinking is that this default behavior of silently failing is what callers would prefer.
assertions continued to be used for types of errors that clients should not be handling, but are rather indicative of a bug. These do not have an error code as they are unexpected faults in the program and therefore should only be handled for purposes like logging, which do not require differentiation among the causes of the assertion violation.
Also introduced a …
=> feat: handle caller errors using errors as values

bridge/qb/server/functions.lua, bridge/qb/server/player.lua, server/player.lua
Assert that qbx_core will not work with qb-inventory and that the user should utilize ox_inventory instead.
=> feat(bridge/qb/server) assertions for deprecated qb-inventory functions

client/character.lua, server/character.lua
Reverts Qbox-project/qbx_core#473
This causes a bug where players are invisible to other players. Not a clean revert. Changed the original code to await the callback to fix the original issue of not having a callback function for the async callback.
=> revert: "refactor(character): Remove callback and use tutorial native."

client/events.lua
Apparently we set this twice cause it's cool. This fixes that and lets the server set it so no shenanigans.
=> fix(client/events): server sets isLoggedIn state

bridge/qb/shared/main.lua, config/server.lua, config/shared.lua, server/character.lua
since this is a shared file, the client copy of the file errors out immediately on script start since its trying to require a file thats not available to the client.
=> fix(bridge/qb/shared/main): context check for requiring server file

locales/da.json
- A curly bracket in the "dv" translation was placed too early. Therefore "params" wasn't being read into "dv".
- Added translations for remaining strings.
- Also, very small grammar mistake fixed.
=> fix(locales/da): Curly bracket misplaced + Translations

modules/logger.lua, server/player.lua
Logging money was lacking in fidelity with the current setup. This provides the ability to send tagged data to ox_lib which enables better parsing and analysis as well as clarifying the direction of change for the SetMoney function (usually triggered by ox_inventory money moves). Also adds the ability to know which resource triggered the add/remove/set money events so you can find that troublesome resource that is paying out too much.
=> refactor(server/player): improve money logging

client/functions.lua, fxmanifest.lua, server/functions.lua, shared/functions.lua
This adds a utility export that allows for a string/table of job/gang/citizenId to be passed against a function and quickly return if the condition matches. Utilizes ox_target code for group/citizenId matching.
=> feat: HasGroup export

config/server.lua
Added two missing data table entries from npwd, these two entries will make sure that all rows from npwd are being properly deleted from the database when deleting a character.
=> fix(config/server): Add missing rows to be deleted

modules/lib.lua
Fixes #501 
- Tested
- Re-ordered operations so that first the vehicle bucket is set, then the player is warped, and then we wait for the vehicle to have an owner (warp is set it wait for the warping player to become the owner) and then the properties are set.
- Ensures that properties are set, or else deletes the vehicle and throws an error.
=> fix(lib): spawn vehicle property setting when warping

server/player.lua
This event will work as handler  like 
```
-- Add any additional event handlers for player logout
-- Server Side
AddEventHandler('qbx_core:server:playerLoggedOut', function(source)
-- Add any additional actions you want to perform when a player logs out
print('Player with source ID ' .. source .. ' has logged out.')
end)
```
- [yes ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ yes] My pull request fits the contribution guidelines & code conventions.
=> add server side playerLoggedOut Event Handler

modules/lib.lua
lib.waitFor throws an error when the timeout is exceeded, so need to pcall it to catch the error.
=> fix(modules/lib): deleting vehicle when unable to find owner or set properties

server/commands.lua, server/player.lua
Asserting that all the commands for job/gang modification are successful so that the error is printed in console if it fails
=> fix: propagate errors for job/gang commands

config/server.lua
When deleting characters this table needs to have rows removed if there is not a FK constraint
=> fix(config/server): remove player_groups row on delete when foreign key constraint is missing

bridge/qb/client/events.lua, client/events.lua, server/loops.lua
Adds statebag handlers to trigger hud updates for compatibility. Not required for qbx_hud but other huds that listen to the legacy NetEvents need these
=> feat(client/events): add handler for triggering hud updates

server/player.lua
Since a player cannot be added/removed from or to the unemployed or none job/gang, this was causing errors.
Fixes #511
=> fix(server/player): setting job/gang to/from unemployed/none

server/commands.lua, server/functions.lua
Fxserver can only handle error() bodies as strings. Fixes an issue preventing the printing of an uncaught error.
=> fix: stringifying assertion errors

server/commands.lua
Removed the unnecessary comments above the commands and sets a type to string.
=> chore(server/commands): remove unnecessary comments

server/character.lua
qb-core stores the charinfo.cid as a string. This won't work with the built in multicharacter due to using the cid as an index value. This fixes that.
=> fix(server/character): return number index for multicharacter

server/functions.lua
There seems to be a weird edge case in ban checking which I believe is the issue in #463.
Currently we pull whichever license the player has (license2 first then license) and then check it against the bans table to see if the individual is banned. If you have an admin menu which bans by license but you have a license2, the check will give a false positive and allow the player through because it did not check by license. This fixes that by first checking by license2 and then by license to make sure we catch both cases.
Feel free to comment or start a discussion below. Idk if there's a better way we'd like to do this.
=> fix(server/functions): ban checking edge case

config/server.lua, server/loops.lua
To help prevent people from having to modify core files and only config files applicable to their installation this PR extracts the paycheck function out to the config to better support various paycheck scripts such as [randol_paycheck](https://github.com/Randolio/randol_paycheck).
=> feat!(config/server): extract paycheck function to config

bridge/qb/server/functions.lua, server/groups.lua
lib.triggerClientEvent offers improved performance for sending client events to multiple clients. This moves events sent to all clients to lib.triggerClientEvent
=> refactor: use lib.triggerClientEvent

bridge/qb/server/functions.lua, server/groups.lua
Reverts Qbox-project/qbx_core#523
This is apparently bait for events that hit -1 and doesn't actually bring any performance increase.
=> Revert "refactor: use lib.triggerClientEvent"

server/player.lua
Comparison operator was in opposite direction causing logs to show "added" cash when it was really removed.
=> fix(server/player): logs add / remove cash correctly via SetMoney

server/storage/players.lua
Adds cleanplayergroups command to remove invalid groups from the player_groups table to prevent issues with PlayerData loading. Additionally checks for group validity during player load to block invalid groups from being inserted into the respective PlayerData.jobs/gangs tables. Fixes #526
=> refactor(server/storage): block non-existent groups from PlayerData

server/functions.lua
Spawning off a thread for the ban insert while functionally correct the natives could fail to return the identifiers preventing the ban from being inserted. This moves the insert into a pcall which will yield until the ban is inserted.
=> fix(server/functions): exploitban yield until ids inserted

server/storage/players.lua
The grade check for valid groups would fail due to not looking in the grades table of a group. This corrects that.
=> fix(server/storage/players): use correct check for group grade

server/character.lua, server/storage/players.lua
oxmysql returns results in the order returned by the sql server. This moves the sort to the SQL server eliminating an extra loop and localized variables as well as addressing an issue with old qbcore dbs being converted to qbox and not showing characters with the builtin multichar.
=> fix(server/character): use sql order by for character returns

client/character.lua, fxmanifest.lua, server/events.lua, server/groups.lua, server/player.lua, server/queue.lua, server/storage/main.lua, server/storage/players.lua, shared/items.lua, shared/locale.lua, shared/vehicles.lua, shared/weapons.lua, types.lua
Finishes adding the rest of the types for `qbx_core`. I intentionally left out the config and module annotations as I figured those should stay where they are. If we think otherwise, I can move those as well.
=> feat(types): everything else

client/character.lua
- Disables the minimap and health/armor bars when in character selection
- Resets `previewCam` when destroyed
=> fix(client/character): disable minimap when in char select

bridge/qb/server/main.lua, bridge/qb/shared/compat.lua, server/main.lua
Next core release is a breaking release that requires external dependencies to be updated. Failing to complete these dependencies should throw loud and obvious warnings to prevent users from connecting to a server in a bad state. This accomplishes that along with moving the print message for item conversion to a thread to print at end of server load.
=> refactor: error conditions and bridge compat

server/player.lua
Dead people shouldn't use weapons while living people can use weapons
canUseWeapons should be inverted from inlaststand and dead metas otherwise you get zombies with guns.
=> refactor(server/main): make error conditions very obvious

server/player.lua
Some older admin resources may pass the grade as a string. We don't use strings for grades so this covers that case and converts them properly
=> fix(server/player): convert grade to number

server/player.lua
Removes the extra `math.abs` as its already being done in the `SetMoney` function so no need to try to do it in the `emitMoneyEvents` function.
=> fix(server/player): money hud updates

server/events.lua
Setting the statebags outside of the core never actually updates the metadata values which other resources may depend on. This corrects that with a guard check to prevent infinite recursion.
=> fix(server/events): statebag handler for hunger/stress/thirst

qbx_core.sql
CitizenID is a generated field that has a charset of A-Z 0-9. Forcing this to a certain collation is counterintuitive as it doesn't support unicode characters. The issue that was supposed to be resolved by this is for the `name` field being unpopulated due to players with unicode characters in their name within the fivem client. This corrects that issue as well as streamlining qb-core users migrating to qbx_core.
=> fix(sql): correct column for unicode enforcement

server/queue.lua
For some reason `GlobalState.MaxPlayers` isn't completely reliable and can sometimes be `nil`, so this gets the convar directly instead.
=> fix(server/queue): get max players via convar for better reliability

server/player.lua
- adding more offline player checks to prevent errors shown in #554. Also likely the root cause of https://github.com/Qbox-project/qbx_management/issues/56
- discovered and fixed a latent bug where setting an offline players' hunger/thirst/stress wouldn't clamp between 0 and 100.
=> fix(server/player): more offline player checks

bridge/qb/server/functions.lua
QBCore offered a method to modify player object functions at runtime which can lead to interesting side effects depending on implementation. This adds warnings for when this occurs and adds options to block the behavior as well as disabling the warning in either case.
In cases where resources override existing functions such as https://github.com/Qbox-project/qbx_core/issues/559 we should throw a warning to advise the user that unintended behavior may occur. We can also provide a convar to selectively disable this behavior as well as the warning.
=> feat(bridge/qb): add warnings and disabling of overridden functions

.gitignore, server/groups.lua, shared/gangs.lua, shared/jobs.lua
A core assumption of jobs/gangs is that they will be named all lower case.
- Adds comments in the config file explaining this
- Adds a server side check on server start to add console error prints if a group name is invalid.
=> feat(server/groups.lua): adds error print if a group name contains capital letters

locales/et.json
- Arguments of a command cannot be named the same
=> fix(locales/et): SetGang command broken for Estonian users

server/player.lua
Fixes issues related to money management when adding money via the player.Function.AddItem/RemoveItem as well as correcting the string passed to ox_inventory during the `emitMoneyEvents()`
=> fix(server/player): ox_inventory money vs cash

client/main.lua
Hashes the vehicle model name before adding it to the table of vehicle classes that will be passed to the server. This seems to be the intention as the server-side `GetVehicleClass` function is documented to take a number for a model, not a string.
=> fix(client/main): hash model names when passing classes to server

client/vehicle-persistence.lua, fxmanifest.lua, modules/lib.lua, server/commands.lua, server/functions.lua, server/vehicle-persistence.lua
fixes #567 
Implements design as described in #567
- Tested
- persistence is disabled by default, requires convar to opt-in.
- Changed places where we delete a vehicle in core to use the new core export.
- We'll need to change other Qbox resources to use the DeleteVehicle export to delete vehicles. This export allows the vehicle to be deleted without being respawned by persistence and works even if persistence is disabled via convar.
Adds new exports
- EnablePersistence
- DisablePersistence
- DeleteVehicle
=> feat: persistent player vehicles

server/main.lua
This fixes 3 issues:
- Calls to this function would *always* send a new client callback for vehicle classes, since non-array tables don't have a length. Fixed by assigning `nil` at first and checking for that.
- `lib.callback.await` is async. This gives potential for multiple callbacks when vehicle classes aren't available, but are still being waited on by other callers. Fixed by creating a new promise, and resolving it when the callback is done.
- If the callback failed for one player, other players may still be available. Fixed by asking different players continuously until there's no players to ask.
Might need more of a discussion on the 2nd point. What should happen if the client can't answer for some reason and the callback times out? Should we return `nil` like in the current …
=> fix(server/main): prevent multiple vehicle classes requests to client

bridge/qb/client/main.lua, bridge/qb/server/functions.lua, bridge/qb/server/main.lua, bridge/qb/server/player.lua, bridge/qb/shared/main.lua, client/events.lua, client/functions.lua, client/main.lua, modules/playerdata.lua, modules/utils.lua, server/commands.lua, server/events.lua, server/functions.lua, server/main.lua, server/player.lua, shared/functions.lua, types.lua
- Adds diagnostic comments to make LLS happy
- Adds `NotificationPosition` and `NotificationType` alias to types.lua to satisfy diagnostics
Once merged, https://github.com/Qbox-project/github-docs/pull/17 will satisfy the last remaining `undefined-global` diagnostic warnings.
If any of these should actually be fixed instead of diagnostically dismissed, feel free to comment or add to this PR.
=> feat: diagnostic comments

modules/lib.lua
Fixes an unreachable function within the `spawnVehicle` function in the lib module. Apparently this has been broken for three months lol
=> fix(modules/lib): unreachable function

server/events.lua, server/player.lua
Previous fix didn't scale properly to higher player counts. This sets the metadata **prior** to the statebag preventing infinite recursion
=> fix(server/events): remove threads from handler

server/main.lua, server/vehicle-persistence.lua
We need a stable vehicle identifier that works for both NPC and player owned vehicles. vehicleid already represents player owned vehicles, so overloading it could cause issues with scripts relying on this behavior. netId would not be stable for persisted vehicles, which have their entities deleted and spawned.
Therefore this PR is introducing a sessionId, which will be incremented starting by 1 to guarantee uniqueness. This will be set via a new export CreateSessionId on the vehicle's state bag, which acquires a lock to guarantee that no two vehicles are assigned the same id. This will be persisted during vehicle persistence.
Also sneaking in a fix to persist vehicleid during vehicle persistence as I realize we never did that before.
While this is being introduced for vehicles, it is …
=> feat: entity session id

server/loops.lua
Fixes erroneous issue where if society account has zero dollars it will still issue a paycheck
=> fix(server/loops): correctly skip if society is too low

client/events.lua, fxmanifest.lua, server/motd.lua
To improve the onboarding of newbies to Qbox, this PR adds:
- Client MOTD sent in the chat after the player loads in; can be configured.
- Server MOTD printed to the console after the server starts; can be disabled.
- Service messages taken from the `txAdminRecipe`, repo printed to the console after the server starts; can be disabled.
Server MOTD example:
See client MOTD and service message examples here: Qbox-project/txAdminRecipe#86
=> feat: motd

server/storage/players.lua
Fixes an issue where a JSON decoding error is thrown when a `citizenid` isn't present in the `players` table when attempting to fetch a player entity.
=> fix(storage/players): Avoid json decoding error when a citizenid doesn't exist

server/vehicle-persistence.lua
getVehicleId yields the thread, so reading the entities state bag needs to happen before then, otherwise the deletion may have already happened by the time we attempt to read the statebag
=> fix(server/vehicle-persistence): get session id while vehicle exists

server/character.lua
What: Added the player's CID to the join log. 
Why: Useful for administrative tasks and debugging.
Does it fix an issue: No
=> feat: Adding player ID to player load log output

config/client.lua
With the new default timeout being increased to 30 seconds in ox_lib, our core config option should reflect that.
I'm also of the opinion that it can now be removed but that's up to yall.
=> fix(client/config): adjust to match ox_lib

server/vehicle-persistence.lua
IsVehicleTyreBurst throws an error if the tire index does not exist and there is no server side native to check if the tire exists.
This handles tire damage the same way as windows and doors; getting the data from the client.
=> fix(vehicle-persistence): use diff provided tyres changes

client/events.lua, modules/lib.lua
After turning off ped warping, I noticed reliability issues with setting vehicle properties on spawned vehicles. This PR aims to improve this reliability and has been tested in Popcorn RP for the past week with no issues. Here are the changes:
**Consistent Ownership**: When a player is put into the driver seat of a vehicle, they become the vehicle owner, and will stay the owner, which prevents race conditions in the async communication of client/server for entity ownership. This acts as a sort of lock on entity ownership. To also have a lock on entity ownership, we assert that the entity owner does not change during prop setting. Asserting this is needed as through debugging prints I observed that multiple clients thought themselves the owner at the same time and attempted to set …
=> fix(lib): vehicle spawning reliability

server/main.lua
This is an optional efficiency improvement as returning large tables can be several ms of runtime.
=> feat(server/main): getter param overloads to get table entry instead of entire table

modules/lib.lua
Use vehicle type if it exists when spawning vehicles to avoid needing to create a temp vehicle. Still keeping the temp vehicle code as a backup in case users don't update their shared/vehicles to include types.
Dependent on https://github.com/Qbox-project/qbx_core/pull/628
=> refactor(lib): use vehicle type when spawning vehicles

server/player.lua
We don't check if players are already logged in before letting them log in. This is bad form and lets folks dupe starter items and cause other issues. This checks if players are logged in and drops them for exploiting and triggers a log message.
=> fix(server/player): prevent login while already logged in

server/player.lua
This PR would add simple `addMoney`, `removeMoney`, `setMoney` hooks for player money methods. It's quite useful, especially for bankings or even other resources who work with money. 
Main reason is because at the moment to support something like `freezing player account`, we've to override `AddMoney`, `RemoveMoney` methods using `AddPlayerMethod` to override those, while trying to keep up with all the compatibility and original code support. With these hooks, new implementation would be simple:
```lua
exports.qbx_core:registerHook('addMoney', function(data)
if data.moneyType ~= 'bank' then return true end
-- check if account should be frozen, from source `data.source`
-- return result
return false
end)
```
=> feat(server/player): add hooks for add/remove/set money methods

server/player.lua
Fixes regression introduced by #618 which kicks players who have a license stored in database, since it doesn't check for db license matching license, only license2.
=> fix(server/player): license login check passes for license and license2

fxmanifest.lua
This is the minimum version which has orphan mode, which we want to use for vehicle persistence
=> chore(fxmanifest): bump minimum required artifact version to 10731

server/player.lua
When deprecating the player.functions.Save, which handles both online and offline players, we replaced it with the Save export function, which only handles online players. Fixed this regression by checking for online/offline status as player.functions.Save does
=> fix(server/player): exports for offline players

modules/lib.lua
This should prevent the most common cause of vehicles being deleted, increasing reliability of persistence. Dependent on https://github.com/Qbox-project/qbx_core/pull/638
Since this is a new native, it's not in the docs nor known by the linter. Added in https://github.com/citizenfx/fivem/pull/2893
=> fix(modules/lib): set entity orphan mode on spawned vehicles to improve vehicle persistence

client/character.lua, client/events.lua
The tutorial natives still seem to be causing issues as we're still getting reports of people unable to see other players. This edit forces the script to wait until the player is in or out of the session before it continues. I've tested this on local but not with other players.
I'm unsure why we're having such a hard time with these TutorialSession natives as ox_core uses them perfectly fine.
=> fix(client): ensure tutorial sessions

server/player.lua
Figured this out after receiving reports that my banking script wasn’t working on QBX correctly.
- Corrected the difference calculation for setMoney. The previous state always returned 0 because the calculation was performed after setting the player's money.
- Pass the amount instead of the difference to setMoney. This aligns with QB, as many scripts, including my banking script, were designed to handle the new amount directly.
- For `RemoveMoney` and `AddMoney`, the difference was incorrectly passed as false for both in `hud:client:OnMoneyChange`. I’m not sure if this is being used, but it should be true for remove and false for add as in `QB`. Used a ternary operator to handle this logic appropriately
=> fix(server/money): setMoney

locales/nl.json
Currently in the dutch language file there is branding for a server called "Infinity", I replaced this 3d party branding with Qbox.
=> Remove server branding from locale

server/functions.lua
This fixes misidentification of string numbers (e.g. "1", "2", "3"), and correctly converts them to source numbers for indexing rather than interpreting it as an identifier.
=> Fixes misidentification of source as an identifier

modules/hooks.lua
This pretty much fixes wrong hooks response.
TLDR: If neither hook fails, expected response is `true`. With current implementation, it returns `nil` which is considered as `false` and will always fail.
Simple example:
```lua
if not triggerEventHooks('removeMoney', {
source = player.PlayerData.source,
moneyType = moneyType,
amount = amount
}) then return false end
```
If there's any hooks registered for `removeMoney`, it will always fail even though hooks return `true`.
=> fix(modules/hooks): return proper response, if neither hook fails

modules/lib.lua
Marks `qbx.playAudio` as deprecated since we now utilize `mana_audio`. Closes #492 upon merging.
=> feat(modules/lib): deprecate qbx.playAudio

modules/lib.lua
This pull request adds a feature to check if a player is wearing a duffel bag.
=> feat(modules): add duffel bag check

client/groups.lua, server/groups.lua, server/player.lua, types.lua
- Make client cache group data from the server on first load. Currently, if any runtime modifications are made to groups before client connection, those changes are not seen by client.
- Update gang grade name when `onGangUpdate` net event is triggered
- Include `bankAuth` in `PlayerData` for gang & job
=> fix(groups): Client cache group data from server in case of runtime modifications

server/player.lua
Handles nested metadata and closes #646. Doesn't allow for more than one level deep. I think there's probably a better way to do this but right now it just checks for periods as seperators.
=> feat(server/player): support getting/setting nested metadata

server/player.lua
Resets a players grade to `0` as a failsafe if the job the player had still exists in the shared, but the grade the player had was deleted.
Closes #682
=> fix(player): Reset Job grade on missing

modules/lib.lua
The function constantly create tempvehicle because it cannot find the right hash and return nil
=> fix(modules/lib): finding the vehicle type in a function for CreateVehicleServerSetter

server/player.lua
Adds the missing exports for 2 functions: `SetPlayerData` and `UpdatePlayerData` as noted by the docs [here](https://docs.qbox.re/resources/qbx_core/exports/server#setplayerdata) and [here](https://docs.qbox.re/resources/qbx_core/exports/server#updateplayerdata)
Closes: #684
=> fix(server/player): Add Missing Exports

modules/lib.lua, modules/utils.lua, server/groups.lua
Allows group updates via server/groups.lua to be committed to the shared resource file(s), allowing for external resources to add persistent changes to groups instead of working around the FiveM sandbox limitations with saving other resource files. Use-case for this can be a server management panel that manages jobs & gangs.
=> feat: persistent group updates

bridge/qb/server/player.lua, client/character.lua, locales/en.json, server/character.lua, server/player.lua
This PR fixes the famous delete character bug, the implemented fix replaces the internal function `DeleteCharacter` by a callback `qbx_core:server:deleteCharacter` ; ensuring data is well received before fetching displaying nonexistent characters.
The notification is handled client-side based on the return value, instead of the server
_Error preview:_
=> fix(server): use callbacks for character deletion

modules/lib.lua, server/commands.lua
Passes the current ped's routing bucket into the `spawnVehicle` function.
Previously, the vehicle's existence was being checked before its routing bucket was set, which resulted in an infinite loop, thus preventing the vehicle from spawning until the player switched back to bucket 0.
Fixes https://github.com/Qbox-project/qbx_core/issues/695
=> fix(server): set routing bucket in car command and vehicle validation

server/functions.lua
Makes this function return something other than false. Apparently I botched this 10 months ago and it wasn't caught. Per the shared data it is should be `isboss` not `IsBoss`
=> fix: use correct variable name for function

types.lua
Add the missing 'type' field to Vehicle class in types.lua.
=> fix(types): add missing 'type' field to Vehicle class

server/functions.lua
change the IsGradeBoss from a nil value to a valid value
it should be merged because it fix a valid issue
more info:
invalid table access to the job grades to get whether or the grade has the isboss attr as a truthy value
=> fixed isGradeBoss exports to return a valid boolean
